export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const CLEAR_USER = "CLEAR_USER";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const CHANGE_EMAIL_SUCCESS = "CHANGE_EMAIL_SUCCESS";
export const CHANGE_EMAIL_FAIL = "CHANGE_EMAIL_FAIL";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const REMOVE_ACCOUNT_SNACKBAR = "REMOVE_ACCOUNT_SNACKBAR";

export const GET_USER_ANALYTICS = "GET_USER_ANALYTICS";
export const GET_ADMIN_ANALYTICS = "GET_ADMIN_ANALYTICS";

export const GET_TOURNAMENTS = "GET_TOURNAMENTS";
export const CREATE_TOURNAMENT = "CREATE_TOURNAMENT";
export const EDIT_TOURNAMENT = "EDIT_TOURNAMENT";
export const DELETE_TOURNAMENT = "DELETE_TOURNAMENT";
export const CLEAR_TOURNAMENTS = "CLEAR_TOURNAMENTS";
export const TOURNAMENTS_ERROR = "TOURNAMENTS_ERROR";

export const GET_SECTIONS = "GET_SECTIONS";
export const CREATE_SECTION = "CREATE_SECTION";
export const EDIT_SECTION = "EDIT_SECTION";
export const DELETE_SECTION = "DELETE_SECTION";
export const CLEAR_SECTIONS = "CLEAR_SECTIONS";
export const SECTIONS_ERROR = "SECTIONS_ERROR";

export const GET_PLAYERS = "GET_PLAYERS";
export const CREATE_PLAYER = "CREATE_PLAYER";
export const EDIT_PLAYER = "EDIT_PLAYER";
export const MOVE_PLAYER = "MOVE_PLAYER";
export const DELETE_PLAYER = "DELETE_PLAYER";
export const PLAYERS_ERROR = "PLAYER_ERROR";

export const GENERATE_PAIRINGS = "GENERATE_PAIRINGS";
export const GET_PAIRINGS = "GET_PAIRINGS";
export const DELETE_PAIRING = "DELETE_PAIRING";
export const UPDATE_RESULT = "UPDATE_RESULT";
export const PAIRING_ERROR = "PAIRING_ERROR";
